name: Build Linux x86

on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    name: Build Linux 32-bit
    runs-on: ubuntu-latest
    container: i386/ubuntu:latest
    continue-on-error: true
    
    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git
        
    - name: Checkout code
      run: |
        git config --global --add safe.directory /__w/SrcDest/SrcDest        
        git init
        git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
        git fetch --depth 1 origin ${{ github.ref }}
        git checkout FETCH_HEAD
        
    - name: Install dependencies
      run: |
        apt-get install -y build-essential autoconf automake libtool pkg-config libsqlite3-dev libxxhash-dev libjansson-dev libcurl4-openssl-dev libssl-dev cmake

    - name: Download and build libwebsockets
      run: |
        apt-get install -y wget
        wget https://github.com/warmcat/libwebsockets/archive/refs/tags/v4.0.20.tar.gz -O libwebsockets-4.0.20.tar.gz
        tar -xzf libwebsockets-4.0.20.tar.gz
        cd libwebsockets-4.0.20
        mkdir build
        cd build
        cmake ..
        make
        make install
    
    - name: Download and compile fswatch
      run: |
        apt-get install -y wget
        wget https://github.com/emcrisostomo/fswatch/releases/download/1.14.0/fswatch-1.14.0.tar.gz
        tar -xzf fswatch-1.14.0.tar.gz
        cd fswatch-1.14.0
        ./configure --prefix=/usr
        make
        make install
        ldconfig
        
    - name: Find fswatch library
      run: |
        echo "/usr/include/libfswatch/c"
        ls -l /usr/include/libfswatch/c
        echo "/usr/lib/*fswatch*"
        ls -l /usr/lib/*fswatch*
        echo "ldconfig" 
        ldconfig -p
        fswatch_lib=$(ldconfig -p | grep 'libfswatch\.so' | head -n 1 | awk '{print $4}')
        fswatch_inc=$(find /usr/include -name 'cevent.h' | head -n 1 | xargs dirname)
        echo "FSWATCH_LIB=-L$(dirname $fswatch_lib)" >> $GITHUB_ENV
        echo "FSWATCH_INC=-I$fswatch_inc" >> $GITHUB_ENV
        
    - name: Build agentc
      working-directory: ./AgentC
      run: gcc agentc.c -o agentc -lsqlite3 -lxxhash -ljansson -lwebsockets ${{ env.FSWATCH_LIB }} -lfswatch ${{ env.FSWATCH_INC }} -lcurl -lssl -lcrypto 

    - name: Copy agentc to dist folder
      run: |
        mkdir -p ./dist
        cp ./AgentC/agentc ./dist/agentc-linux-x86

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet HEAD; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add ./dist/agentc-linux-x86
        git commit -m "Add agentc-linux-x86 to dist folder"
        git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
     
