name: Build Linux x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build Linux 64-bit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev libxxhash-dev libjansson-dev libwebsockets-dev fswatch libcurl4-openssl-dev libssl-dev
        
    - name: Find fswatch library
      run: |
        fswatch_dir=$(dpkg -L fswatch | grep libfswatch)
        fswatch_lib="${fswatch_dir}/libfswatch.so"
        echo "FSWATCH_LIB=$fswatch_lib" >> $GITHUB_ENV

    - name: Build agentc
      working-directory: ./AgentC
      run: gcc agentc.c -o agentc -lsqlite3 -lxxhash -ljansson -lwebsockets ${{ env.FSWATCH_LIB }} -lcurl -lssl -lcrypto
      
    - name: Upload agentc as artifact
      uses: actions/upload-artifact@v4
      with:
        name: agentc-linux-x64
        path: ./AgentC/agentc
