name: Count Lines of Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_linux_x64:
    name: Build Linux 64-bit
    uses: ./.github/workflows/Build-Linux-x64.yml
    secrets: inherit

  cloc:
    runs-on: ubuntu-latest
    needs: build_linux_x64
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@main
      with:
        options: --report-file=cloc.txt

    - run: csplit README.md /\<\!--CLOC/ {1}
    - run: cp xx00 README.md
    - run: echo "<!--CLOC-START -->" >> README.md
    - run: echo "\`\`\`" >> README.md
    - run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
    - run: echo "Last Updated at ${{ env.NOW }}" >> README.md
    - run: tail -n +2 cloc.txt >> README.md
    - run: echo "\`\`\`" >> README.md
    - run: cat xx02 >> README.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        skip_dirty_check: true            
        branch: main
        file_pattern: 'README.md'
